### ISSUE TITLE
How to support drag sorting?

### ISSUE THREAD

**Issue by xhzengAIB** [kuler90/RKTagsView#1]
Hello！@kuler90

If drag some tag, how to support rearrange all tags?

Jack

**Comment by kuler90** [comment]
Hi Jack!
Thank you for the question. To support drag and drop I added two methods: for getting tag index by point and for moving tag. With this methods you can use [this](https://www.raywenderlich.com/63089/cookbook-moving-table-view-cells-with-a-long-press-gesture) dragging implementation. See release 1.1.0
