### ISSUE TITLE
emojis cutting

### ISSUE THREAD

**Issue by Luccifer** [kuler90/RKTagsView#14]
![screen shot 2017-08-02 at 14 19 12](https://user-images.githubusercontent.com/1053009/28869381-969c8b44-778d-11e7-9e99-31b230fea341.png)

Hello! I tried a lot of things, but maybe you can give me a clue how to fix it. I stopped here:

`

func tagsView(_ tagsView: RKTagsView, buttonForTagAt index: Int) -> UIButton {
        
        let tagButton = UIButton()
        tagButton.isSelected = false
        tagButton.isUserInteractionEnabled = false
        tagButton.titleLabel?.font = UIFont(name: "Circe-Regular", size: 12)
        tagButton.tintColor = UIColor.black.withAlphaComponent(0.25)
        tagButton.titleLabel?.lineBreakMode = .byTruncatingTail
        tagButton.setTitle(tagsView.tags[index], for: .normal)
        tagButton.titleLabel?.textColor = UIColor.white.withAlphaComponent(0.8)
        tagButton.backgroundColor = UIColor.black.withAlphaComponent(0.25)
        tagButton.setTitleColor(UIColor.white.withAlphaComponent(0.8), for: .normal)
        tagButton.sizeToFit()
        tagButton.contentEdgeInsets = UIEdgeInsetsMake(2, 6, 2, 6)
        tagButton.titleEdgeInsets = UIEdgeInsetsMake(2, 2, 2, 2)
        tagButton.clipsToBounds = false
        tagButton.titleLabel?.clipsToBounds = false
        tagButton.isExclusiveTouch = false
        tagButton.frame.size.height = 24
        tagButton.layer.cornerRadius = 8
        return tagButton
    }

`

**Comment by kuler90** [comment]
Hi, this should help - https://stackoverflow.com/a/38356719

**Comment by Luccifer** [comment]
Not works..

This actually helped a lot: 

        guard let text = tagButton.titleLabel?.text else {return UIButton()}

        let attributtedString = NSMutableAttributedString(string: text)

        let pStyle = NSMutableParagraphStyle()

        pStyle.lineSpacing = 2

        pStyle.minimumLineHeight = 18

        pStyle.maximumLineHeight = 22

        attributtedString.addAttribute(NSParagraphStyleAttributeName, value: pStyle, range: NSRange(location: 0, length: attributtedString.string.characters.count))

        tagButton.titleLabel?.attributedText = attributtedString
