### ISSUE TITLE
Add spaces in tags?

### ISSUE THREAD

**Issue by docash59** [kuler90/RKTagsView#21]
Is there a way to add spaces like "`firsName lastName`" rather than every time I press 'space' it adds a new tag?

**Comment by oNguyenNgocBan** [comment]
I have the same question, I want add new tag when user type a comma?

**Comment by bannn-1018** [comment]
You can change deliminater character by:
`self.tagsView.deliminater = [NSCharacterSet characterSetWithCharactersInString:@","];`
