### ISSUE TITLE
How to combine with autocomplete?

### ISSUE THREAD

**Issue by buiminhhuy** [kuler90/RKTagsView#3]
I want to searchable on textfield of RKTagsView to show list suggestion, after selecting a item from list, the item will add to RKTagsView.
How to implement above scenario? Thanks for advance help.

**Comment by kuler90** [comment]
Hi!
You can use delegate (it is free) or add action for UIControlEventEditingChanged on the textfield. After selecting an item from list you can use methods addTag or insertTag.

**Comment by buiminhhuy** [comment]
Thanks.
