### ISSUE TITLE
RKTagsView in TableViewController with Auto Layout

### ISSUE THREAD

**Issue by vmish** [kuler90/RKTagsView#4]
Hi Roman,

Have you tried to use RKTagsView in TableViewController with Auto Layout? Unfortunately, it doesn't work as expected in my project. May be I've missed something:

``` objective-c
- (void)viewDidLoad
{
    ...
    self.tableView.rowHeight = UITableViewAutomaticDimension;
    self.tableView.estimatedRowHeight = 44.0;
    ...
}
```

``` objective-c
- (UITableViewCell *)tableView:(UITableView *)tableView cellForRowAtIndexPath:(NSIndexPath *)indexPath
{
    ...
    cell.tagsViewHeightConstraint.priority = 1;
    [cell.tags addTag:@"tag"];
    [cell layoutIfNeeded];
    ...
}
```

**Comment by kuler90** [comment]
Hi Victor,

RKTagsView should work in TableViewController with Auto Layout. It uses the same mechanism that UILabel and UITextView. I think that you have problem with constraint priorities. You don't need height constraint. You can set your height constraint in Interface Builder as Placeholder. In example I use two height constraint and switch between them by changing priority. Also you should don't forget to set bottom constraint to cell.

**Comment by vmish** [comment]
Hi Roman,

All constraint are set correctly. Also I remove unnecessary height constraint. Unfortunately, the issue still persists.

But this workaround helps me:

``` objective-c
- (void)viewWillAppear:(BOOL)animated
{
    [super viewWillAppear:animated];
    [self.tableView reloadRowsAtIndexPaths:[self.tableView indexPathsForVisibleRows] withRowAnimation:UITableViewRowAnimationNone];
}
```

Nevertheless, thank you for your feedback!

**Comment by muhammad-zohaib-ehsan** [comment]
Hi Guys
I am also trying to get it work in tableview. But it is not working. As pointed by @kuler90 I have setup the constraints properly. 
I populate the tags view with some pre defined tags. Cells are self sizing. But its still not working. 
Any help will be highly appreciated.
Thanks
