### ISSUE TITLE
Update tagsViewHeight Constraint inside uitableviewcell

### ISSUE THREAD

**Issue by alhazme** [kuler90/RKTagsView#5]
Hi Roman,
How to update tagsViewHeight.constant if tagsView inside contentview of UITableViewCell?
I've tried update tagsViewHeight.constant in tagsViewContentSizeDidChange function, but still not working.

Thanks

**Comment by kuler90** [comment]
Hi!

Height constraint uses to restrict height. If you need dynamic height you don't need it. Pay attention to constraints priorities, content hugging priority and content compression resistance priority.
RKTagsView implement method "intrinsicContentSize" which is used by Auto Layout for calculating view size. UILabel and UITextView (with disabled scroll) work at the same way. You can read about them.
