### ISSUE TITLE
Make random tags selectable

### ISSUE THREAD

**Issue by fisfej** [kuler90/RKTagsView#9]
Great job first of all.

I need use it in a different way. Is it possible to make some tags selectable and the rest not.?

**Comment by kuler90** [comment]
Thanks! Yes, you can use the delegate method:
`- (BOOL)tagsView:(RKTagsView *)tagsView shouldSelectTagAtIndex:(NSInteger)index; `

**Comment by fisfej** [comment]
Thanks i didn't noticed that, i fixed it. But i have another question, how to make the selected buttons, with custom views, i need to use dropdown menu on the selected buttons. Any advice ?

**Comment by kuler90** [comment]
I think you can create custom button which implement dropdown as subview and use it in method
`- (UIButton *)tagsView:(RKTagsView *)tagsView buttonForTagAtIndex:(NSInteger)index;`

**Comment by fisfej** [comment]
I have tried this way, but i cant make a UIView subview of UIButton!

**Comment by kuler90** [comment]
You can add dropdown view inside button as subview because UIButton inherits from UIControl which inherits from UIView. You can work with UIButton as with UIView.
